### PR TITLE
Add build status in readme.

### PR DESCRIPTION
**Pull request by plumsky**

### CODE REVIEW

**Comment by zeromus** [comment]
Uhmmm shouldn't we integrate that on github and just link to github from the readme instead? that would be cleaner

**Comment by plumsky** [comment]
Ok, that better, I close this.

**Comment by zeromus** [comment]
well, create an issue for it at least, so the author knows you want him to try setting up the integration for the travis badge on github

**Comment by plumsky** [comment]
@zeromus 
OK, thanks advice, I add an issue https://github.com/albertodemichelis/squirrel/issues/126

**Pull request closed without merging**
