### PR TITLE
Normalize whitespace.

### PR DESCRIPTION
**Pull request by mfxmfx**
Strip trailing whitespace, de-tabify and ensure that each file
ends with a newline.

### CODE REVIEW

**Comment by zeromus** [comment]
Why does it matter whether documentation files end with newlines?

**Comment by mfxmfx** [comment]
In a shared development environment whitespace issues are a continuous source of noise and merge conflicts.

And many editors automatically strip trailing whitespace and add a missing newline at the end of the file.

**Comment by zeromus** [comment]
An editor that does that for an unknown file type is a really dumb editor.

**Comment by mfxmfx** [comment]
Actually this is becoming common and supported by many tools, see e.g. usage of http://editorconfig.org/ at https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig .

**Comment by zeromus** [comment]
Users who configure their editorconfig to format unknown file types are really dumb users.

**Pull request merged**
