### PR TITLE
Fix building with DISABLE_DYNAMIC on *nix

### PR DESCRIPTION
**Pull request by jansol**
Looks like #79 somehow missed this one.

### CODE REVIEW

**Comment by paulsapps** [comment]
Weird, I had it building on osx and linux via Travis-CI. Speaking of which I wonder if its worth enabling travis/appveyor on this repo?

**Comment by jansol** [comment]
Did your travis enable DISABLE_DYNAMIC?

**Comment by paulsapps** [comment]
Yeah thats why I added it to speed up the build a little

**Comment by paulsapps** [comment]
I also had to put this change in #86 so if that PR gets approved there will probably be a merge conflict..

**Comment by jansol** [comment]
Closing in favour of #86.

**Pull request closed without merging**
