### PR TITLE
Various improvements of the build system

### PR DESCRIPTION
**Pull request by FabianWolff**
- I rewrote the CMake files so that they work under Windows using Visual Studio. I also improved their Linux behavior. My files are confirmed to work with MSVC12 (Windows), gcc5.3 and ARMgcc4.6 (both Linux, see README). Under Windows, you need the quite recent version 3.4 of CMake to build the shared libraries, though, because Squirrel does not export any DLL symbols by default, and the CMake option to export everything into the DLL has just been adopted into v3.4. As long as you don't use MSVC, it only asks for CMake v2.8.
- I tested Squirrel on a few more platforms and added them to the README. Most notably, I confirmed that Squirrel can run on ARM.
- I fixed every warning gcc 5.3.1 generates if the flags -Wall and -Wextra are specified. It now compiles cleanly on my system (amd64).

### CODE REVIEW

**Comment by albertodemichelis** [comment]
the change in squirrel/sqcompiler.cpp will break in a release build as "assert((hasattrs && ((hasattrs ? _fs->PopTarget():-1) == key-1)) || !hasattrs);" will eliminated in a released build

can you put back the old code for this change? the rest looks ok

**Comment by albertodemichelis** [comment]
it looks that there a conflicts with the current version, can you take a look?

**Comment by FabianWolff** [comment]
Yes, the whitespace was wrong. I'm on Linux, but the sources now seem to be using DOS-Style \r\n line endings. It should be fixed now.

**Comment by mfxmfx** [comment]
Hi,
I've also rewritten the CMake file - please have a look at 

https://github.com/mfxmfx/squirrel/commits/travis

and 

https://travis-ci.org/mfxmfx/squirrel

Maybe we can coordinate our efforts?

**Comment by FabianWolff** [comment]
Sure. My intention with rewriting the CMake files was mainly to make them work with Windows/MSVC, as having CMake files is somewhat useless if they only work under one platform.

Having had a quick glance at your CMakeLists.txt file, I identified problems with both yours and mine:
- I doubt your file is going to work under Windows with MSVC. You check $CPPFLAGS, and that's not normally available under Windows (to my knowledge). Also, I think you'll find that since the Squirrel code does not export its symbols via __dllexport() (or similar, not sure), MSVC will fail to create a DLL that you can actually link against.
- You put it all into one file instead of using subdirectories. This is not the usual CMake policy, but as long as it works, I guess it's fine (although one may want to discuss readability issues).
- I did not include an option that turns `-DSQUNICODE` on.
- You build only one library, my CMakeLists.txt and the official Makefiles create both libsquirrel and libsqstdlib.

I've checked my files on three platforms (Linux amd64, Windows MSVC x86, Linux ARM) and they worked, so I don't think there's any reason to throw them away, but if you have useful additions to make, I say go ahead.

**Comment by mfxmfx** [comment]
Hi Fabian,

* I tested both clang & gcc under i386, amd64, arm & powerc
* Builds static and shared libraries
* Supports "make install"
* Builds cleanly with -Werror under travis in 20 configurations
* More travis cross-toolchains can be added easily
* MSVC should also work - with -W4, and SQUNICODE is supported as well
* For such small projects one central CMakeLists.txt is enough - no need to clutter
* FYI, CPPFLAGS is a standard-style Unix envvar and is passed down from travis_build.sh
* Applies cleanly without noise.

So may I suggest that Alberto pulls my tree and you base your remaining improvements (compilation warnings, additional MSVC tunings) on that ?

Cheers,
Markus

**Comment by FabianWolff** [comment]
> - Builds static and shared libraries
> - Supports "make install"
> - Builds cleanly with -Werror

So does mine.

> - MSVC should also work - with -W4, and SQUNICODE is supported as well

Yeah, but that was not my point. I said that Squirrel does not explicitly export symbols into DLLs and that you consequently cannot create a DLL that you can link against. Trust me, I've tried it, and yes, the library builds just fine, it's just that you can't do anything with it.

> - FYI, CPPFLAGS is a standard-style Unix envvar and is passed down from travis_build.sh

Not sure what Travis has to do with this, but yes, CPPFLAGS *is* a standard Unix environment variable, but since Windows is not a Unix-like system, it does not matter.

If Alberto is happy with my changes so far, I'd ask him to merge them as they are right now - I've got other things to do, so I don't want to rebase my entire pull request, and honestly, if you see the need to use your CMake files, it should not be very hard to just delete mine, possibly copy some lines, and then base your request on that. As long as your files provide the same functionality, I got what I wanted, didn't I?

**Comment by mfxmfx** [comment]
>>   MSVC should also work - with -W4, and SQUNICODE is supported as well

> Yeah, but that was not my point. I said that Squirrel does not explicitly export symbols into DLLs and that you consequently cannot create a DLL that you can link against. Trust me, I've tried it, and yes, the library builds just fine, it's just that you can't do anything with it.

Indeed - and that's why my cmake file says 
```
if(WIN32 OR WIN64)
    set(ENABLE_SHARED OFF)
   ...
endif()
```
Did you actually have a careful look ??

**Comment by FabianWolff** [comment]
Sorry, I did indeed miss that line. But since you can, in fact, build proper shared libraries under Windows, as my CMake files demonstrate, I don't see why you would want to just disable that functionality. But I don't want to start a fight on this - I'm keeping my files now, and if you feel like there's something inherently wrong with them, it's your liberty to go ahead and change that.

**Comment by mfxmfx** [comment]
Yeah, let's Alberto decide how he wants to proceed - we have the same goals anyway.

**Comment by albertodemichelis** [comment]
This is thought decision to make. I don't use and I don't like CMake. I'm ok to add a few files in the project because I understand that some people like it.
I cannot be the judge here, I want to bless 3.1 stable this week so if this is not solve the CMake files will remain what are now.
About Travis CI, as far as no files from Squirrel's sources are touched I can add a couple of .sh, but please leave the README alone.

**Comment by mfxmfx** [comment]
No problem - I will keep the cmake & travis changes in a private branch for now.

But please have a look at my "silence-warnings" pull request.

**Comment by FabianWolff** [comment]
One big problem I would like to see fixed before 3.1.0 is the encoding and whitespace issue: This is the second time I had to adjust my pull request because someone pushed a file with different encoding/whitespace in the meantime. Having to fix these things manually is error-prone, time-consuming and makes the diffs unnecessarily big. Maybe mfxmfx could revisit this (I think it was you who already attempted this a while ago). I would also be fine with DOS-style line endings, but either way, consistency is key here. Currently, I don't even know what kind of encoding it's supposed to be - my editor reads it as Unix-style, but there are definitely loads of \r\n line endings still in there.

Other than that, I doubt that either one of our CMake file sets would be a regression from the current state, but I definitely see why you would want to wait with this. Just let me know whether I should reset them for this specific pull request so you can merge it in time and still get the other changes into 3.1.0.

**Comment by mfxmfx** [comment]
Whitespace issues should already be fixed in the master branch - Unix EOL, no hard tabs and no trailing whitespace (with exceptions for Makefiles and *.ds[pw]).

**Comment by FabianWolff** [comment]
I thought so, too, but then why does GitHub keep complaining about it? I'll try to rebase my commits on top of the current master branch, maybe that'll fix it.

**Comment by mfxmfx** [comment]
Your current cmake branch dc4eb2a is a mess because of your broken merge commit.

Please rebase your changes on albertodemichelis/master with a new one that **only changes the cmake files** and leaves all other files alone.

Also you may want to add -Wcast-qual to the warning flags.

**Comment by FabianWolff** [comment]
I added -Wcast-qual to the g++ flags, although it does not currently have any effect (it still builds cleanly without warnings).

What do you mean with "broken merge commit"? It says right here that "This branch has no conflicts with the base branch", and that reflects my personal expectation after having done precisely what you want me to do: Rebasing my changes off the current master branch. I also can't find any abnormalities in the diffs - the only changes I made are changes in regard to the compiler warnings (mostly, if not exclusively, -Wunused-parameter), changes that, by the way, I proposed before you came along with a pull request that did pretty much the exact same thing. In my opinion, it's better style to annotate the parameter names than to comment them out, but that's just my opinion, so if Alberto wants me to change that, I can do that. But right now, I fail to see your problem.

**Comment by mfxmfx** [comment]
Just because there are no conflicts that does not mean that a pull can be a mess - you have undone half of my silence-warnings pull request which got merged a few days ago.

Just run ```git diff 3090721 e9f7d4f``` (which means ```git diff  alberto/master fabian/cmake```) to see what I mean.

**Comment by FabianWolff** [comment]
I did not "undo" your changes, I just implemented them differently (incidentally, that happened long before you even created your pull request). It seems that you are unfamiliar with the term "Free Software", so here is some material to get you started:

http://www.gnu.org/philosophy/free-sw.html

**Pull request merged**
