### PR TITLE
Introduce null-coalescing and null propagation operators

### PR DESCRIPTION
**Pull request by VasiliyRyabtsev**
Add new operator ?? such that
  a ?? b
works as
  (a!=null) ? a : b

C#-like ?? syntax was chosen over Elvis operator ?: which is common in other languages because it is not equivalent to visually similar ternary ? : operator (which checks for falsiness, not null).

It evaluates expressions until the first non-null value (just like || operators for the first 'true' one)

Operator precendence is also follows C# design, so that ?? has lower priority than ||

Null propagation operators ?. and ?[] are similar to ones in C# 6.0 or Kotlin

```
local tbl = {bar=123}
tbl.bar     // returns 123
tbl.baz     // throws an error
tbl?.bar    // returns 123
tbl?.baz    // returns null
null.bar    // throws an error
null?.bar   // returns null
tbl?["bar"] // returns 123
tbl?[4567]  // returns null
```

This works for any type (internally done via SQVM::Get(), like an 'in' operator), including null.

This adds new opcodes: _OP_NULLGET and _OP_NULLCOALESCE.

### CODE REVIEW

**Comment by todace** [comment]
@albertodemichelis what do you think of this?
I find it very useful

**Comment by RizzoRat** [comment]
There was a discussion in the forums on such topic a while ago I remember, and this looks like a good solution for the issue.
I'd agree, it's useful. (Did no code review tho)

**Comment by albertodemichelis** [comment]
I'm not sure I agree with this two changes.

About the ??.
I don't see how a ?? b is different than a || b

About the .?
It can already be solved with existing semantics and adds 2 instructions.

This is straight from my current game codebase
```
//common.nut
local _DefaultNullGetDelegate = {
	function _get(key) { 
		return null; 
	}
}
//calling this function on a table makes it return null when the key doesn't exists
function SetDefaultNullGetDelegate(table)
{
	table.setdelegate(_DefaultNullGetDelegate);
	return table;

}
....

//is used like this
local tbl = SetDefaultNullGetDelegate({bar=123})

tbb.bar    // returns 123
tbl.baz    // returns null

```
This also allows different behaviors/default values, so is somewhat more flexible.

Alberto

**Comment by zeromus** [comment]
`a || b` syntax has a smell like "truthiness" from lua and JS which is not one of their greatest features. It is not clear what || means to arguments that arent booleans. You have to check the reference manual and think about it every time.  It is not intuitive at all. I mean, I could make a coffee table book "101 illustrated ways to interpret various operands to ||" and still have enough ideas left for a sequel.

The difference is (false || b) is b; whereas (false ?? b) is false. This would be preferable to someone who agrees with me and uses a || b only when he is confident that a and b are booleans because || is madness in any other case.

I agree with you more on null propagation. It picks one special way of handling null index on a table and privileges it. Personally, I use a `automatically return 0 or empty string` handling, and default `why did you use a null index? that's a mistake. please crash now` handling far, far, far, far more often than I use a `automatically return null` handling. I am generally OK with copying c# and don't want to really argue with any proposal to copy c#, but the proposal here lacks some of the power of c#, leaving only what can already be done in squirrel natively. (what about `tbl?.baz()`? what about `mylocal?.baz()`?). I like copying c# so much that I don't want to "promise" someone it's been done, and then have it fall surprisingly short.

**Comment by RizzoRat** [comment]
( `tbl?.baz()` may lead to an exception "attempt to call null", that's okay and responsibility of the programmer)
However you have a point, as much as I'd like some syntactic sugar to avoid the `(foo in bar)?bar.foo:null `expression I find myself using over and over, and the fact that sometimes delegation is not always suitable in complex situations - (including native class instances).

BTW: I disagree to your opinion about the || operator, zeromus (it's absolutely clear what it does in squirrel, and the rules are the same like the expressions `foo` or `!foo` - null is false, false is false and 0 is false, everything else is true. Dead simple.

I guess both is just a matter of taste

**Comment by zeromus** [comment]
I should mention also there's probably an operator precedence difference between || and ??. One would have to more commonly write (a||b) in complex expressions, whereas a??b would typically be fine. What I mean, is when in combination with my general suspicions about what || means in squirrel, there is my additional normal suspicions of any complex logic expressions without lots of parentheses. I could be wrong about what ?? means, but I think it causes less alarm and less need for parentheses.

**Comment by todace** [comment]
Hello @albertodemichelis 
Just to notice - there are proposals for both operators to include in ECMAScript
see 
https://github.com/tc39/proposal-nullish-coalescing and https://github.com/TC39/proposal-optional-chaining
While JS is often "when in doubt do the opposite way of JS", but this is also how it works in C# or some other languages.
I have to mention that we use both operators really A LOT it saves time and make world better place to live.
Regards

**Comment by todace** [comment]
BTW (about delegates solution) - we implemented small optimization in squirrel to work faster on get from tables when no delegates are present (except defaults), and win some % of performance with few lines of code.

**Comment by todace** [comment]
@zeromus optional call method ( ?.() ) can be done the same manner

**Comment by VasiliyRyabtsev** [comment]
Merged into fork https://github.com/GaijinEntertainment/quirrel

**Pull request closed without merging**
