### PR TITLE
Add userdata pointer to functions

### PR DESCRIPTION
**Pull request by frabert**
Adds an additional argument to C functions in order to pass an additional pointer to arbitrary data, which allows - for example - to implement closures from C. ~~`sq_newclosure` is augmented in order to reflect this.~~
A new function `sq_newudclosure` is added in order to support this.

~~This is a breaking change - existing codebases will refuse to compile. Maybe an auxiliary way can be found to render the additional parameter optional.~~

### CODE REVIEW

**Comment by VasiliyRyabtsev** [comment]
Why not use free variables?

**Comment by frabert** [comment]
Mainly ease of use and conciseness, no need to push and pop stuff from the stack.

**Comment by frabert** [comment]
I made the API backwards compatible by wrapping existing `SQFUNCTION`s with an auxiliary function.

**Comment by zeromus** [comment]
Seems like a cool idea to me even though there's a workaround. With the new function added, the only possible objection would be an extra pointer stored with the closure, maybe not used by some people. This is a very small objection (literally) but maybe larger if the data is wasted on pure squirrel closures. (just thinking out loud here)

**Comment by frabert** [comment]
@zeromus If it turns out it's a significant issue, I guess it could be hidden behind some ugly preprocessor flag to render it optional

**Pull request closed without merging**
