### PR TITLE
Removing dead code in sq_call

### PR DESCRIPTION
**Pull request by iSLC**

### CODE REVIEW

**Comment by zeromus** [comment]
are you working through the results of some static analysis tool, or do you have a better reason for finding this stuff?

**Comment by iSLC** [comment]
Uhm, not really. I was simply looking at how the function was implemented. Simply to get a better understanding of how the provided API works. Then noticed the unnecessary return. And upon further look I noticed the code after the first if/else is never reached because both branches of the if/else had a return at the end of their scope.

If the original behavior was actually intended, then I apologize for the mistake and you may close the PR.

**Comment by zeromus** [comment]
No, it looked like an old mistake due to changing code to me. I just wanted to apply appropriate context. Sometimes people start posting 100s of fixes due to static analyzers and haven't properly investigated or tested anything. It seems like you investigated this adequately though

**Comment by mingodad** [comment]
I did a test using it in SquiLu but it make the tests fail, so this patch doesn't seem to be correct.

**Pull request merged**
