### PR TITLE
Update of sqstdlib

### PR DESCRIPTION
**Pull request by atanasovdaniel**
Hello,

There is my proposal to update sqstdlib. Documentation is updated also.

API changes:

- SQFILE now represents a SQSTREAM to file, not FILE*.
 SQFILE is created by sqstd_fopen() and is released by sqstd_fclose().
 Functions sqstd_createfile() and sqstd_getfile() still use FILE*.
 Two new functions sqstd_createsqfile() and sqstd_getsqfile() to create/get
  SQFILE object to/from instance of file class.

- SQSTREAM is base clas of blob, file, streamreader, textreader and textwriter.
 SQSTREAM adds new API functions: sqstd_sread, sqstd_swrite,
 sqstd_sseek, sqstd_stell, sqstd_sflush, sqstd_seof, sqstd_sclose
 and sqstd_srelease.

- Two more methods are added to SQStream to help generalization of stream:
 Close and _Release. Method _Release is called by sqstd_srelease() and by
 stream release hooh.
 
- The pointer to SQRegClass structure is used as type tag.

API added:

- Three function are added to iteract with streams - sqstd_loadstream,
 sqstd_compilestream, sqstd_readclosurestream and sqstd_writeclosuretostream.

- New SQTStreamReader is implemented based on SQStream. Stream reader gives
 ability to virtualy 'mark' and 'reset' position of readed SQStream.
	Functions added: sqstd_streamreader, sqstd_srdrmark, sqstd_srdrreset

- Text reader/writter based on SQStream with support for ASCII, UTF-8,
 UTF-16BE, UTF-16LE. Two functions to create streams sqstd_textreader and
 sqstd_textwriter.

- Declaration helpers: sqstd_registerclass, sqstd_registermembers and
 sqstd_registerfunctions. Also structures to describe class/members
 declarations - SQRegMember and SQRegClass.

From scripting side:

- Added loadstream, dostream and writeclosuretostream.
- 'stream' class has two new methods - print and readline
- Added 'streamreader' calss.
- Added 'textreader' and 'textwriter' calss.

### CODE REVIEW

**Comment by paulsapps** [comment]
There are conflicts, you at least need to rebase this before it can be looked at..

**Comment by zeromus** [comment]
Looks kind of cool, worth investigating further

**Comment by atanasovdaniel** [comment]
Now it is rebased and no conflicts.

**Comment by paulsapps** [comment]
MSVC has a warning:

C:\sq\sqstdlib\sqstdio.cpp(71): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)

**Comment by zeromus** [comment]
Can you provide some kind of summary as to the overall concept here? I know I said it looks cool, but I can't remember what it does now -_-

**Comment by atanasovdaniel** [comment]
I updated my first comment with more info

**Comment by zeromus** [comment]
OK, this still seems pretty cool to me, except, the API changes are probably too large until a squirrel 3.2, for anyone who likes keeping APIs compatible (which isn't me, for what it's worth).

**Comment by atanasovdaniel** [comment]
I have updated the SQFILE API. Actually now it is almost exactly as the original one.
And also is more simple.

**Comment by atanasovdaniel** [comment]
Zeromus, yes API changes are to large to be included in current version. And my work is still not mature enough. But i hope that for next versions it will be.

**Pull request closed without merging**
