### PR TITLE
switch to CMake build system

### PR DESCRIPTION
**Pull request by M1cha**

### CODE REVIEW

**Comment by albertodemichelis** [comment]
I'm fine adding CMake files however I don't want to remove make files as I don't use CMake.

**Comment by M1cha** [comment]
I just thought that it would be redundant since u can generate Makefiles and even VisualStudio projects using cmake.

But if you're not ready to switch to cmake I can keep the Makefiles ofc.

**Comment by megrooms** [comment]
CMake is a great option to have. It makes moving between Linux, BSD, OSX & Windows trivial. Not to mention, the config file syntax is super easy to work with. A welcome addition IMO.

**Comment by M1cha** [comment]
@albertodemichelis a question about _SQ64: is that just a VM thing or is it absolutely required when compiling for a 64bit target?
I configured CMake to detect 64bit compilers and automatically set this flag then.

**Comment by albertodemichelis** [comment]
Yep you should set _SQ64 for 64 bits to work on all OSs without to rely on _LP64 or _WIN64 etc...

**Comment by M1cha** [comment]
I've updated the commit to keep the Makefiles :)

**Pull request merged**
