### PR TITLE
fix #36 releasehook APIs and docs fixes

### LINKED ISSUE #36: Weird code in sq_setreleasehook and sq_getreleasehook
Why do these functions check sq_gettop()? They don't care about the structure of the stack. Based on my research this used to check for a stack size in excess of 2 a few versions ago (don't understand the purpose of that) and from there it went all the way back to the first squirrel version.

There don't seem to be any other functions doing similar checks; I imagine this was detritus from an early version of squirrel which had sq_set/get releasehook operating on the stack top instead of a given index?

I think the checks should simply be removed.

example:

```
void sq_setreleasehook(HSQUIRRELVM v,SQInteger idx,SQRELEASEHOOK hook)
{
//    if(sq_gettop(v) >= 1) //needless
{
        SQObjectPtr &ud=stack_get(v,idx);
        switch( type(ud) ) {
        case OT_USERDATA:   _userdata(ud)->_hook = hook;    break;
        case OT_INSTANCE:   _instance(ud)->_hook = hook;    break;
        case OT_CLASS:      _class(ud)->_hook = hook;       break;
        default: break; //shutup compiler
        }
    }
}
```

### PR DESCRIPTION
**Pull request by zeromus**
tidy sq_setreleasehook and sq_getreleasehook (fixes #36)
fix various typos and incompletely apply very lightweight formatting (continued)
I did not realize github would incorporate these other commits automatically into the PR:
Add virtual dtor to SQStream and add make more uniform some light error checking to sqstdlib for some things that tripped me up

### CODE REVIEW

**Comment by albertodemichelis** [comment]
I'm not sure I like the "table expected" in the api registration functions, I can think of someone wanting to do something funky with a class or instance. The rest is all good, thank you :)

**Comment by zeromus** [comment]
I see now my analysis was somewhat muddled: I modeled the error checking after declare_stream on accident which already had that check, thinking it was a top-level registration function. But then, isn't it sensible to check in sqstd_register_iolib() then since it's using declare_stream() as a dependency; and then sensible by analogy with the other registration functions? But you make a good point, I have no strong opinion.

**Comment by zeromus** [comment]
edits to registration function removed

**Comment by albertodemichelis** [comment]
you forgotten the iolib :)

**Comment by zeromus** [comment]
son of a gun. sorry, fixed that commit. but i left the check in sqstd_dofile()...

**Pull request merged**
